version: "3"
services: 
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app # bind mount (no need to specify entire path)
      - /app/node_modules # anonymous volume
    environment:
      - NODE_ENV=development
    command: npm run dev

# docker-compose -f docker-compose.yaml -f docker-compose-dev.yaml up -d
# docker-compose -f docker-compose.yaml -f docker-compose-dev.yaml down -v
