# With yaml files spacing matters
version: "3"
services: 
  node-app: # container name
    build: . #current diectly (automate build command)
    ports:
      - "3000:3000"  
    environment:  # without env will work as we have added those in Dockerfile
      - PORT=3000

# contains common config for both dev and prod env